config/routes.rb
Rails.application.routes.draw do

  devise_for :shops, controllers: {
    registrations: 'owner/registrations',
    sessions: 'owner/sessions'
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  
  # ゲスト
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  
  # 共通画面
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'signup' => 'public/homes#signup', as: 'signup'
  get 'login' => 'public/homes#login', as: 'login'

  #一般ユーザー
  scope module: :public do
    get '/users/:id/mybookmark' => 'users#mybookmark', as: 'users_mybookmark'
    get '/users/:id/myfavorite' => 'users#myfavorite', as: 'users_myfavorite'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
    resources :users, only: [:show, :edit, :update]
    get '/shops/:id/photos' => 'shops#shop_photos', as: 'shop_photos'
    resources :photos, only: [:index, :show] do
      resources :photo_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :cats, only: [:index]
      resources :events, only: [:show]
      resources :shop_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get "search_form" => "searches#search_form"
  end

  # 店舗オーナー
  namespace :owner do
    resources :shops, only: [:show, :edit, :update] do
      resources :shop_comments, only: [:destroy]
    end
    get '/shops/:id/unsubscribe' => 'shops#unsubscribe', as: 'shops_unsubscribe'
    patch '/shops/:id/withdraw' => 'shops#withdraw', as: 'shops_withdraw'
    resources :cats
    resources :photos do
      resources :photo_comments, only: [:destroy]
    end
    resources :events
  end

  # サイト管理者
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops, only: [:index, :show, :edit, :update]
  end

end

app/models/photo.rb
class Photo < ApplicationRecord

  belongs_to :shop
  has_many :photo_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 200 }
  # validates :image, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # 画像を中心点からwidth,heightサイズに切り取り
      image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法の分岐
  def self.search_for(keyword, method)
    if method == "perfect"
      Photo.where("content LIKE?", "#{keyword}")
    elsif method == "forward"
      Photo.where("content LIKE?", "#{keyword}%")
    elsif method == "backward"
      Photo.where("content LIKE?", "%#{keyword}")
    else
      Photo.where("content LIKE?", "%#{keyword}%")
    end
  end
end

app/controllers/owner/cats_controller.rb
class Owner::CatsController < ApplicationController
  before_action :authenticate_shop!
  before_action :is_matching_login_shop, only: [:show, :edit, :update, :destroy]

  def new
    @cat = Cat.new
  end

  def index
    @cats = current_shop.cats.page(params[:page]).per(6)
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.shop_id = current_shop.id
    if @cat.save
      flash[:notice] = "新規登録に成功しました！"
      redirect_to owner_cat_path(@cat.id)
    else
      flash.now[:alert] = "新規登録に失敗しました"
      render :new
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to owner_cat_path(@cat.id)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    flash[:notice] = "卒業に成功しました！"
    @cat.destroy
    redirect_to owner_cats_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :gender, :feature, :introduction, :image)
  end
  
  # ログインしている店舗ユーザー以外の情報へアクセスした場合トップページへ
  def is_matching_login_shop
    cat = Cat.find(params[:id])
    unless cat.shop_id == current_shop.id
      redirect_to root_path
    end
  end
end

app/controllers/owner/confirmations_controller.rb
# frozen_string_literal: true

class Owner::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/owner/events_controller.rb
class Owner::EventsController < ApplicationController
  before_action :authenticate_shop!
  before_action :is_matching_login_shop, only: [:show, :edit, :update, :destroy]
  
  def index
    @events = current_shop.events
    @event = Event.new
    # 今月のイベント情報の絞り込み
    @current_month_events = current_shop.events.where(start_time: Time.now.all_month)
  end
  
  def create
    @event = Event.new(event_params)
    @event.shop_id = current_shop.id
    if @event.save
      flash[:notice] = "新規登録に成功しました！"
      redirect_to owner_events_path
    else
      @events = current_shop.events
      flash.now[:alert] = "新規登録に失敗しました"
      render :index
    end
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    @event.shop_id = current_shop.id
    if @event.update(event_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to owner_event_path(@event.id)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    flash[:notice] = "削除に成功しました！"
    @event.destroy
    redirect_to owner_events_path
  end
  
  
  private
  
  def is_matching_login_shop
    event = Event.find(params[:id])
    unless event.shop_id == current_shop.id
      redirect_to root_path
    end
  end
  
  def event_params
    params.require(:event).permit(:title, :content, :start_time)
  end
end

app/controllers/owner/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Owner::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/owner/passwords_controller.rb
# frozen_string_literal: true

class Owner::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/owner/photo_comments_controller.rb
class Owner::PhotoCommentsController < ApplicationController
  
  def destroy
    @photo = Photo.find(params[:photo_id])
    PhotoComment.find(params[:id]).destroy
  end
  
end

app/controllers/owner/photos_controller.rb
class Owner::PhotosController < ApplicationController
  before_action :authenticate_shop!
  before_action :is_matching_login_shop, only: [:show, :edit, :update, :destroy]
  
  def new
    @photo = Photo.new
  end
  
  def index
    @photos = current_shop.photos.page(params[:page]).per(6)
  end
  
  def create
    @photo = Photo.new(photo_params)
    @photo.shop_id = current_shop.id
    if @photo.save
      flash[:notice] = "新規投稿に成功しました！"
      redirect_to owner_photo_path(@photo.id)
    else
      @photos = current_shop.photos
      flash.now[:alert] = "新規投稿に失敗しました"
      render :new
    end
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to owner_photo_path(@photo.id)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    flash[:notice] = "投稿の削除に成功しました！"
    @photo.destroy
    redirect_to owner_photos_path
  end
  
  private
  
  def is_matching_login_shop
    photo = Photo.find(params[:id])
    unless photo.shop_id == current_shop.id
      redirect_to root_path
    end
  end
  
  def photo_params
    params.require(:photo).permit(:title, :content, :image)
  end
  
end

app/controllers/owner/registrations_controller.rb
# frozen_string_literal: true

class Owner::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :address, :phone_number, :opening, :closed])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :name_kana, :address, :phone_number, :opening, :closed])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    owner_shop_path(current_shop)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/owner/sessions_controller.rb
# frozen_string_literal: true

class Owner::SessionsController < Devise::SessionsController
  before_action :shop_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def after_sign_in_path_for(resource)
    owner_shop_path(current_shop)
  end

  # 退会しているかを判断するメソッド
  def shop_state
    @shop = Shop.find_by(email: params[:shop][:email])
    if @shop
      if @shop.valid_password?(params[:shop][:password]) && (@shop.active_for_authentication? == false)
        flash[:error] = '退会済みです。'
        redirect_to new_shop_session_path
      end
    end
  end
end

app/controllers/owner/shop_comments_controller.rb
class Owner::ShopCommentsController < ApplicationController
  
  def destroy
    @shop = current_shop
    ShopComment.find(params[:id]).destroy
  end
  
end

app/controllers/owner/shops_controller.rb
class Owner::ShopsController < ApplicationController
  before_action :authenticate_shop!
  before_action :set_shop
  before_action :is_matching_login_shop

  def show
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to owner_shop_path(@shop)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    if @shop.update(is_deleted: true)
      reset_session
      flash[:notice] = "正常に退会しました。ご利用ありがとうございました。"
      redirect_to root_path
    end
  end


  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  # ログインしている店舗ユーザー以外の情報へアクセスした場合トップページへ
  def is_matching_login_shop
    shop_id = params[:id].to_i
    unless shop_id == current_shop.id
      redirect_to root_path
    end
  end

  def shop_params
    params.require(:shop).permit(:name, :email, :address, :phone_number, :opening, :closed, :image)
  end

end

app/controllers/owner/unlocks_controller.rb
# frozen_string_literal: true

class Owner::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/owner/cats_helper.rb
module Owner::CatsHelper
end

app/helpers/owner/comments_helper.rb
module Owner::CommentsHelper
end

app/helpers/owner/events_helper.rb
module Owner::EventsHelper
end

app/helpers/owner/photos_helper.rb
module Owner::PhotosHelper
end

app/helpers/owner/shops_helper.rb
module Owner::ShopsHelper
end

app/views/owner/photos/_comment.html.erb
<% if @photo.photo_comments.present? %>
  <% photo.photo_comments.each do |photo_comment| %>
    <div class="row position-relative justify-content-center m-5 bg-white">
        <div class="col-md-4 p-md-4 text-center">
          <%= image_tag photo_comment.user.get_image(100,100), class: "bd-placeholder-img w-75 rounded m-3" %>
        </div>
        <div class="col-md-8 position-static p-4 pl-md-0 text-left">
          <div class="ml-3">
            <p class="mt-4">
              <% if photo_comment.user.is_deleted == false %>
                -<%= photo_comment.user.name %>さんのコメント-
              <% else %>
                -退会済みユーザーのコメント-
              <% end %>
            </p>
            <p class="mx-2"><%= safe_join(photo_comment.comment.split("\n"), tag(:br)) %></p>

            <p class="text-right">
              <%= link_to owner_photo_photo_comment_path(photo.id, photo_comment.id), method: :delete, remote: true, class: "btn btn-danger btn-sm" do %>
                削除する<i class="fas fa-trash-alt"></i>
              <% end %>
            </p>
          </div>
        </div>
    </div>
  <% end %>
<% else %>
  <h5 class="text-center m-5">まだコメントはありません。</h5>
<% end %>

app/views/owner/photos/edit.html.erb
<div class='container-fluid'>
  <div class='row justify-content-center'>
    <div class='col-md-4'>
      <h1 class='mb-5 text-center'>- PHOTO EDIT -</h1>
      <%= render "layouts/errors", model: @photo %>
      <%= form_with model: @photo, url: owner_photo_path(@photo.id), method: :patch do |f| %>
      <div>
        <table class='table text-center table-borderless table-responsive-md'>
          <tr>
            <td>写真</td>
            <td><%= f.file_field :image %></td>
          </tr>
          <tr>
            <td>タイトル</td>
            <td><%= f.text_field :title, class: 'form-control' %></td>
          </tr>
          <tr>
            <td>投稿内容</td>
            <td><%= f.text_area :content, class: 'form-control' %></td>
          </tr>
        </table>
        <p class="text-center"><%= f.submit "編集を保存する", class: "btn btn-secondary" %></p>
        <p class="text-right"><%= link_to '一覧へもどる', owner_photos_path, class: 'btn btn-info' %></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/owner/photos/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">

    <div class="col-12 clearfix mb-3">
      <h1 class="text-center">- MY PHOTOS -</h1>
      <div class="float-right"><%= link_to '新規投稿する', new_owner_photo_path, class: 'btn btn-info' %></div>
    </div>
    
    <% if @photos.present? %>
      <% @photos.each do |photo| %>
        <div class="col-md-4">
          <div class='card card-columns mb-4'>
            <div class="bd-placeholder-img card-img-top">
              <%= image_tag photo.get_image(600,400), class: "img-fluid img" %>
            </div>
            <div class="card-body">
              <h4><%= photo.title %></h4>
              <p class="card-text text-truncate">
                <%= photo.content %>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to '編集', edit_owner_photo_path(photo.id), class: "btn btn-sm btn-outline-secondary"%>
                  <%= link_to '削除', owner_photo_path(photo.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-sm btn-outline-secondary' %>
                  <%= link_to '詳細', owner_photo_path(photo.id), class: 'btn btn-sm btn-outline-secondary' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-md-12">
        <div class="d-flex justify-content-center mt-5"><%= paginate @photos %></div>
      </div>
    <% else %>
      <h3 class="text-center">
        投稿した写真はありません。<br>
        在籍しているねこちゃんの写真や、<br>
        お店の写真を投稿して魅力を発信しませんか？
      </h3>
    <% end %>
  </div>
</div>

app/views/owner/photos/new.html.erb
<div class='container-fluid'>
  <div class='row justify-content-center'>
    <div class='col-lg-6'>
      <h1 class='mb-3 text-center'>- PHOTO NEW -</h1>
      <%= render "layouts/errors", model: @photo %>
      <%= form_with model: @photo, url: owner_photos_path, method: :post do |f| %>
      <div>
        <table class='table text-center table-borderless table-responsive-md'>
          <tr>
            <td style='width: 30%'>写真</td>
            <td style='width: 50%'><%= f.file_field :image %></td>
          </tr>
          <tr>
            <td>タイトル</td>
            <td><%= f.text_field :title, class: 'form-control' %></td>
          </tr>
          <tr>
            <td>投稿内容</td>
            <td><%= f.text_area :content, class: 'form-control' %></td>
          </tr>
        </table>
        <p class="text-center"><%= f.submit '投稿する', class: 'btn btn-secondary' %></p>
        <p class="text-right"><%= link_to '一覧へもどる', owner_photos_path, class: 'btn btn-info' %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/owner/photos/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mb-5">
      <h1 class="mb-5 text-center">- PHOTO DETAIL -</h1>
      <div class="card mb-4">
        <div class="bd-placeholder-img card-img-top">
          <%= image_tag @photo.get_image(600,400), class: "img-fluid img" %>
        </div>
        <div class="card-body">
          <h4><%= @photo.title %></h4>
          <p class="card-text">
            <%= safe_join(@photo.content.split("\n"),tag(:br)) %>
          </p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <%= link_to '編集する', edit_owner_photo_path(@photo.id), class: "btn btn-sm btn-outline-secondary"%>
              <%= link_to '削除する', owner_photo_path(@photo.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-sm btn-outline-secondary' %>
            </div>
            <p class="text-right"><small>投稿日：<%= @photo.created_at.strftime('%Y年%m月%d日') %></small></p>
          </div>
        </div>
      </div>
      <h1 class="text-center mt-5">- COMMENTS -</h1>
        <div class="row d-flex justify-content-center">
          <div class="col-md-12 <%= "comment-index" + @photo.id.to_s %>">
            <%= render "owner/photos/comment", photo: @photo %>
          </div>
        </div>
      <div class="col-12">
        <div class="text-right"><%= link_to '一覧へもどる', owner_photos_path, class: "btn btn-info" %></div>
      </div>

    </div>
  </div>
</div>