config/routes.rb
Rails.application.routes.draw do

  devise_for :shops, controllers: {
    registrations: 'owner/registrations',
    sessions: 'owner/sessions'
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  
  # ゲスト
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  
  # 共通画面
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'signup' => 'public/homes#signup', as: 'signup'
  get 'login' => 'public/homes#login', as: 'login'

  #一般ユーザー
  scope module: :public do
    get '/users/:id/mybookmark' => 'users#mybookmark', as: 'users_mybookmark'
    get '/users/:id/myfavorite' => 'users#myfavorite', as: 'users_myfavorite'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
    resources :users, only: [:show, :edit, :update]
    get '/shops/:id/photos' => 'shops#shop_photos', as: 'shop_photos'
    resources :photos, only: [:index, :show] do
      resources :photo_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :cats, only: [:index]
      resources :events, only: [:show]
      resources :shop_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get "search_form" => "searches#search_form"
  end

  # 店舗オーナー
  namespace :owner do
    resources :shops, only: [:show, :edit, :update] do
      resources :shop_comments, only: [:destroy]
    end
    get '/shops/:id/unsubscribe' => 'shops#unsubscribe', as: 'shops_unsubscribe'
    patch '/shops/:id/withdraw' => 'shops#withdraw', as: 'shops_withdraw'
    resources :cats
    resources :photos do
      resources :photo_comments, only: [:destroy]
    end
    resources :events
  end

  # サイト管理者
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops, only: [:index, :show, :edit, :update]
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cats, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_one_attached :image
  
  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :opening, presence: true
  validates :closed, presence: true


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  # shopのis_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  # 検索方法の分岐
  def self.search_for(keyword, method)
    if method == "perfect"
      Shop.where("name LIKE?", "#{keyword}")
    elsif method == "forward"
      Shop.where("name LIKE?", "#{keyword}%")
    elsif method == "backward"
      Shop.where("name LIKE?", "%#{keyword}")
    else
      Shop.where("name LIKE?", "%#{keyword}%")
    end
  end
  
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_shop, except: [:index]
  
  def index
    @shops = Shop.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end
  
  def update
    if @shop.update(shop_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to admin_shop_path(@shop.id)
    else
      flash[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end
  
  private
  
  def set_shop
    @shop = Shop.find(params[:id])
  end
  
  def shop_params
    params.require(:shop).permit(:name, :email, :address, :phone_number, :opening, :closed, :image, :is_deleted)
  end
end

app/controllers/owner/shops_controller.rb
class Owner::ShopsController < ApplicationController
  before_action :authenticate_shop!
  before_action :set_shop
  before_action :is_matching_login_shop

  def show
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to owner_shop_path(@shop)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    if @shop.update(is_deleted: true)
      reset_session
      flash[:notice] = "正常に退会しました。ご利用ありがとうございました。"
      redirect_to root_path
    end
  end


  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  # ログインしている店舗ユーザー以外の情報へアクセスした場合トップページへ
  def is_matching_login_shop
    shop_id = params[:id].to_i
    unless shop_id == current_shop.id
      redirect_to root_path
    end
  end

  def shop_params
    params.require(:shop).permit(:name, :email, :address, :phone_number, :opening, :closed, :image)
  end

end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop/passwords_controller.rb
# frozen_string_literal: true

class Shop::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop/registrations_controller.rb
# frozen_string_literal: true

class Shop::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/sessions_controller.rb
# frozen_string_literal: true

class Shop::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/shop/unlocks_controller.rb
# frozen_string_literal: true

class Shop::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/owner/shops_helper.rb
module Owner::ShopsHelper
end

app/views/admin/shops/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <h3 class="mb-5 text-center">-<%= @shop.name + "の登録情報の編集" %>-</h3>
      <%= render "layouts/errors", model: @shop %>
      <%= form_with model: @shop, url: admin_shop_path(@shop.id), method: :patch do |f| %>
      <table class="table">
        <tr>
          <td>店舗名</td>
          <td><%= f.text_field :name, class: "form-control" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email, class: "form-control" %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= f.text_field :address, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.text_field :phone_number, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>営業日</td>
          <td><%= f.text_field :opening, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>定休日</td>
          <td><%= f.text_field :closed, class: 'form-control' %></td>
        </tr>
        <tr>
          <td>店舗画像</td>
          <td><%= f.file_field :image %></td>
        </tr>
        <tr>
          <td>登録状況</td>
          <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted_false, "登録中" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted_true, "退会済み" %>
          </td>
        </tr>
      </table>
      <div class="text-center mt-5">
        <%= f.submit "保存する", class: "btn btn-secondary mr-5" %>
        <%= link_to "一覧へ戻る", admin_shops_path, class: "btn btn-info ml-5" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shops/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 text-center">
      <h3 class="mb-5">店舗一覧</h3>
      <table class="table">
        <tr>
          <th>店舗ID</th>
          <th>店舗名</th>
          <th>メールアドレス</th>
          <th>登録状況</th>
        </tr>
        <% @shops.each do |shop| %>
        <tr>
          <td><%= shop.id %></td>
          <td><%= link_to shop.name, admin_shop_path(shop.id) %></td>
          <td><%= shop.email %></td>
          <% if shop.is_deleted == false %>
            <td class="text-success">登録中</td>
          <% else %>
            <td class="text-danger">退会済み</td>
          <% end %>
        </tr>
        <% end %>
      </table>
      <div class="d-flex justify-content-center mt-4"><%= paginate @shops %></div>
    </div>
  </div>
</div>

app/views/admin/shops/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-7">
      <h3 class="mb-5 text-center"><%= @shop.name + "の店舗詳細情報" %></h3>
      <table class="table">
        <tr>
          <td>店舗ID</td>
          <td><%= @shop.id %></td>
        </tr>
        <tr>
          <td>店舗名</td>
          <td><%= @shop.name %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @shop.email %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @shop.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @shop.phone_number %></td>
        </tr>
        <tr>
          <td>営業日</td>
          <td><%= @shop.opening %></td>
        </tr>
        <tr>
          <td>定休日</td>
          <td><%= @shop.closed %></td>
        </tr>
        <tr>
          <td>画像</td>
          <td><%= image_tag @shop.get_image(150,100) %></td>
        </tr>
        <tr>
          <td>登録状況</td>
          <% if @shop.is_deleted == false %>
            <td class="text-success">登録中</td>
          <% else %>
            <td class="text-danger">退会済み</td>
          <% end %>
        </tr>
      </table>
      <div class="text-center mt-5">
        <%= link_to "編集する", edit_admin_shop_path(@shop.id), class: "btn btn-secondary mr-5" %>
        <%= link_to "一覧へ戻る", admin_shops_path, class: "btn btn-info ml-5" %>
      </div>
    </div>
  </div>
</div>