config/routes.rb
Rails.application.routes.draw do

  devise_for :shops, controllers: {
    registrations: 'owner/registrations',
    sessions: 'owner/sessions'
  }

  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions'
  }
  
  # ゲスト
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end
  
  # 共通画面
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'signup' => 'public/homes#signup', as: 'signup'
  get 'login' => 'public/homes#login', as: 'login'

  #一般ユーザー
  scope module: :public do
    get '/users/:id/mybookmark' => 'users#mybookmark', as: 'users_mybookmark'
    get '/users/:id/myfavorite' => 'users#myfavorite', as: 'users_myfavorite'
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'users_unsubscribe'
    patch '/users/:id/withdraw' => 'users#withdraw', as: 'users_withdraw'
    resources :users, only: [:show, :edit, :update]
    get '/shops/:id/photos' => 'shops#shop_photos', as: 'shop_photos'
    resources :photos, only: [:index, :show] do
      resources :photo_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :shops, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
      resources :cats, only: [:index]
      resources :events, only: [:show]
      resources :shop_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get "search_form" => "searches#search_form"
  end

  # 店舗オーナー
  namespace :owner do
    resources :shops, only: [:show, :edit, :update] do
      resources :shop_comments, only: [:destroy]
    end
    get '/shops/:id/unsubscribe' => 'shops#unsubscribe', as: 'shops_unsubscribe'
    patch '/shops/:id/withdraw' => 'shops#withdraw', as: 'shops_withdraw'
    resources :cats
    resources :photos do
      resources :photo_comments, only: [:destroy]
    end
    resources :events
  end

  # サイト管理者
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :shops, only: [:index, :show, :edit, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :photo_comments, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guestuser'
    end
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_user.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      # 画像を中心点からwidth,heightサイズに切り取り
      image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end

  # userのis_deletedがfalseならtrueを返す
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, except: [:index]
  
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = "編集の保存に成功しました！"
      redirect_to admin_user_path(@user.id)
    else
      flash.now[:alert] = "編集の保存に失敗しました"
      render :edit
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6">
      <h3 class="mb-5 text-center">-<%= @user.name + "さんの登録情報の編集" %>-</h3>
      <%= render "layouts/errors", model: @user %>
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
      <table class="table">
        <tr>
          <td>ユーザー名</td>
          <td><%= f.text_field :name, class: "form-control" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email, class: "form-control" %></td>
        </tr>
        <tr>
          <td>登録状況</td>
          <td>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted_false, "登録中" %>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted_true, "退会済み" %>
          </td>
        </tr>
      </table>
      <div class="text-center mt-5">
        <%= f.submit "保存する", class: "btn btn-secondary mr-5" %>
        <%= link_to "一覧へ戻る", admin_users_path, class: "btn btn-info ml-5" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 text-center">
      <h3 class="mb-5">ユーザー 一覧</h3>
      <table class="table">
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>登録状況</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to user.name, admin_user_path(user.id) %></td>
          <td><%= user.email %></td>
          <% if user.is_deleted == false %>
            <td class="text-success">登録中</td>
          <% else %>
            <td class="text-danger">退会済み</td>
          <% end %>
        </tr>
        <% end %>
      </table>
      <div class="d-flex justify-content-center mt-4"><%= paginate @users %></div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-5">
      <h3 class="mb-5 text-center"><%= @user.name + "さんの詳細情報" %></h3>
      <table class="table">
        <tr>
          <td>ユーザーID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td>ユーザー名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>登録状況</td>
          <% if @user.is_deleted == false %>
            <td class="text-success">登録中</td>
          <% else %>
            <td class="text-danger">退会済み</td>
          <% end %>
        </tr>
      </table>
      <div class="text-center mt-5">
        <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-secondary mr-5" %>
        <%= link_to "一覧へ戻る", admin_users_path, class: "btn btn-info ml-5" %>
      </div>
    </div>
  </div>
</div>